### ISSUE TITLE
Error with different fonts

### ISSUE THREAD

**Issue by EduardoWS** [Akascape/CTkTable#105]
When I make a table with a header with different fonts of other lines, I can't change some table configurations. 

In my case, I made a table that change the number of columns when the user access a different button in the segmented buttons. However, since the font is not the same in the entire table, the following error occurs and I cannot resolve it:

```bash

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\eduar\Documents\Dev\Work\WMS\wms-env\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "c:\Users\eduar\Documents\Dev\Work\WMS\src\screens\ScreenRegistrations.py", line 74, in <lambda>
    command=lambda i=i: self.show_content_screen(i))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\eduar\Documents\Dev\Work\WMS\src\screens\ScreenRegistrations.py", line 99, in show_content_screen
    self.create_content_table(i)
  File "c:\Users\eduar\Documents\Dev\Work\WMS\src\screens\ScreenRegistrations.py", line 189, in create_content_table
    self.table_manager.insert_table_values(i)
  File "c:\Users\eduar\Documents\Dev\Work\WMS\src\managers\RegistrationsTableManager.py", line 71, in insert_table_values
    self.insert_sectors_datas(index)
  File "c:\Users\eduar\Documents\Dev\Work\WMS\src\managers\RegistrationsTableManager.py", line 208, in insert_sectors_datas
    self.content_table.configure(column=self.table_columns)
  File "C:\Users\eduar\Documents\Dev\Work\WMS\wms-env\Lib\site-packages\CTkTable\ctktable.py", line 655, in configure
    self.update_values(self.values, **kwargs)
  File "C:\Users\eduar\Documents\Dev\Work\WMS\wms-env\Lib\site-packages\CTkTable\ctktable.py", line 352, in update_values
    self.draw_table(**kwargs)
  File "C:\Users\eduar\Documents\Dev\Work\WMS\wms-env\Lib\site-packages\CTkTable\ctktable.py", line 254, in draw_table
    self.frame[i,j] = customtkinter.CTkButton(self.inside_frame, background_corner_colors=corners,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: customtkinter.windows.widgets.ctk_button.CTkButton() got multiple values for keyword argument 'font'

```

**Comment by Dumbliidore** [comment]
I have the same error.
