### ISSUE TITLE
.configure of Row and Column Atribute

### ISSUE THREAD

**Issue by JanVasko1** [Akascape/CTkTable#116]
Hello, I found during building the table that in the .configure I cannot configure the "row" and "column" atribute. maybe it would be that code currently is:
![image](https://github.com/user-attachments/assets/a6447acb-e835-4684-b043-d29f1488b064)

but Atribute it self is without "s"
![image](https://github.com/user-attachments/assets/48cf5558-1f34-4534-9055-a87a713962ab)

Shouldn't this help?: 
![image](https://github.com/user-attachments/assets/36d38572-2431-45a7-b42d-ea68204c56f8)

**Comment by JanVasko1** [comment]
Unfortunatelly there is still issue (I created another test and found that closing was wrong) as if I set Values inside .self of CTkTable it is working, but in the case I need to .configure it is not working. 

**Here is my code for testing:**
```python
import customtkinter
from CTkTable import *

root = customtkinter.CTk()

value = [
        "Lunch",
        "Private",
        "Teambulding",
        "Teambuilding",
        "Home Office",
        "Car Blocker",
        "Grilovačka",
        "Christmas party",
        "Deadline pro TimeSheet",
        "KONTROLA DOCHÁZKY",
        "Save the date ",
        "On-Call Duty",
        "TimeSheets - Upload"]

Show_Skip_Events_list = []
for skip_Subject in value:
    Show_Skip_Events_list.append([skip_Subject])


# Working code
table1 = CTkTable(master=root, column=1, row=len(value), values=Show_Skip_Events_list)
table1.pack(expand=True, fill="both", padx=20, pady=20)

# Not Working code
table2 = CTkTable(master=root)
table2.configure(columns=1, rows=len(value), values=Show_Skip_Events_list)

table2.pack(expand=True, fill="both", padx=20, pady=20)
root.mainloop()
```

it always ended here:
![image](https://github.com/user-attachments/assets/9bcb39aa-a499-4ae3-a2be-3d19ceeb2a84)

**Error:** 
Traceback (most recent call last):
  File "d:\KM-Calendar_Reading\test.py", line 32, in <module>
    table2.configure(columns=1, rows=len(value), values=Show_Skip_Events_list)
  File "C:\Users\CZ011845\AppData\Local\Programs\Python\Python311\Lib\site-packages\CTkTable\ctktable.py", line 623, in configure
    self.data[i,j]["args"].update(kwargs)
    ~~~~~~~~~^^^^^
KeyError: (2, 0)
