### ISSUE TITLE
edit cells 

### ISSUE THREAD

**Issue by sim2511** [Akascape/CTkTable#13]
Hello, is it possible to edit cells like Ctktextbox or CtkEntry from the graphic interface

**Comment by Akascape** [comment]
@sim2511 
Not for now, but I will add it soon.

**Comment by Akascape** [comment]
@sim2511 
Please update the package, now you can edit cells by adding the `write=1` parameter to the ctktable.
![Screenshot](https://github.com/Akascape/CTkTable/assets/89206401/7d7c766f-5d3d-4449-9ee1-cdaaa693fa8a)

**Comment by sim2511** [comment]
you are a boss lol

**Comment by sim2511** [comment]
When you put this parameter the width of the cells does not adapt to the length of the text. 
It does without this parameter

**Comment by FrancescoTalotta** [comment]
Hello, 

I get an error when I add `write=1`. Here it is the code: 

```
table11 = CTkTable(master=left5_frame, values=elettronica_orders, header_color="#2A8C55", hover_color="#B4B4B4", font=('Arial', 13), command=t3, write=1)
table11.edit_row(0, text_color="#fff", hover_color="#2A8C55")
table11.edit_column(1, width=10)
table11.pack(expand=False, pady=3)
```
and here the output error: 
```
Traceback (most recent call last):
  File "/Users/francesco/invetory.py", line 580, in <module>
    table11.edit_row(0, text_color="#fff", hover_color="#2A8C55")
  File "/opt/homebrew/lib/python3.11/site-packages/CTkTable/ctktable.py", line 328, in edit_row
    self.frame[row, i].configure(require_redraw=True, **kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/customtkinter/windows/widgets/ctk_entry.py", line 253, in configure
    super().configure(require_redraw=require_redraw, **kwargs)  # configure CTkBaseClass
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/customtkinter/windows/widgets/core_widget_classes/ctk_base_class.py", line 133, in configure
    check_kwargs_empty(kwargs, raise_error=True)
  File "/opt/homebrew/lib/python3.11/site-packages/customtkinter/windows/widgets/utility/utility_functions.py", line 18, in check_kwargs_empty
    raise ValueError(f"{list(kwargs_dict.keys())} are not supported arguments. Look at the documentation for supported arguments.")
ValueError: ['hover_color'] are not supported arguments. Look at the documentation for supported arguments.
```
If I delete `table11.edit_row(0, text_color="#fff", hover_color="#2A8C55")` I get no errors but I get a not very nice looking table.

**Comment by Akascape** [comment]
@FrancescoTalotta You cannot pass hover_color with write=1
