### ISSUE TITLE
Using .insert() or .edit_column() results in error

### ISSUE THREAD

**Issue by dishb** [Akascape/CTkTable#22]
```
Traceback (most recent call last):
  File "/Users/dishb/Repositories/ScreenExtend/screen_extend.py", line 161, in <module>
    app = ScreenExtend(1200, 900)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dishb/Repositories/ScreenExtend/screen_extend.py", line 62, in __init__
    self.devices = Devices(self, self.font)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dishb/Repositories/ScreenExtend/widgets/devices.py", line 62, in __init__
    self.add_device("device 2", "ip 2")
  File "/Users/dishb/Repositories/ScreenExtend/widgets/devices.py", line 83, in add_device
    self.table.add_row(values = new_row,
  File "/Users/dishb/Repositories/ScreenExtend/widgets/CTkTable/ctktable.py", line 231, in add_row
    self.draw_table(**kwargs)
  File "/Users/dishb/Repositories/ScreenExtend/widgets/CTkTable/ctktable.py", line 165, in draw_table
    self.frame[i,j] = customtkinter.CTkButton(self, background_corner_colors=corners,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: customtkinter.windows.widgets.ctk_button.CTkButton() got multiple values for keyword argument 'fg_color'
```

I'm calling the `.edit_column()` method right after creating a row with the default `fg_color`. In the `.edit_column()` method, I specify  the `fg_color` as "red".

**Comment by Akascape** [comment]
@dishb Fixed.

**Comment by dishb** [comment]
I still get the same error.
