### ISSUE TITLE
CTkTable.add_row() raising TypeError

### ISSUE THREAD

**Issue by devandvn** [Akascape/CTkTable#56]
I had created a table using CTkTable with 7 columns and 1 row and  later within a function tried to add a new row with .add_row(index, values), but this raised the error `TypeError: 'list' object cannot be interpreted as an integer`

Code Snippet:
```
dsply_frame = ctk.CTkScrollableFrame(display_tab)
dsply_frame.grid(row=0,column=0,sticky='nsew')
value = [['ID', 'Name', 'Address', 'Phone', 'Gender', 'Class', 'No. of books rented']]
member_table = CTkTable(dsply_frame, row=1, column=7, values=value)
member_table.grid(row=0, column=0, sticky='nsew')

n = 0
def load_more():
    global n
    members = display_members(10,n)
    if members != 0:
        for i in range(len(members)):
            print(list(members[i]))
            member_table.add_row(i, list(members[i]))
        n += 10

load_more_btn = ctk.CTkButton(dsply_frame, text='Load More', command=load_more)
load_more_btn.grid(row=1, column=0, sticky='nse', padx=15,pady=15)

```

Output with full Error: 
```
[1, 'John Doe', '123 Main Street', 4598465494, 'Male', 1, 1]
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/home/user1/.local/lib/python3.11/site-packages/customtkinter/windows/widgets/ctk_button.py", line 554, in _clicked
    self._command()
  File "/home/user1/Projects/Library/source/main3.py", line 244, in load_more
    member_table.add_row(i, list(members[i]))
  File "/home/user1/.local/lib/python3.11/site-packages/CTkTable/ctktable.py", line 240, in add_row
    self.values.insert(index, values)
TypeError: 'list' object cannot be interpreted as an integer
```
This error is probably because of my lack of knowledge of how to properly add a row with .add_row() in which case any help regarding it would be appreceated

**Comment by devandvn** [comment]
Not passing index in the .add_row(index, values) did the trick for me. I dont understand what the index argument is for. Any explanation is appreceated! Thanks.
