### ISSUE TITLE
_tkinter.TclError: invalid command name ".!ctkframe.!ctkframe2.!canvas.!ctkscrollableframe.!ctkframe2.!ctkframe.!canvas.!ctkxyframe.!ctktable.!ctkframe.!ctkbutton5.!ctkcanvas"`

### ISSUE THREAD

**Issue by Adhitya-02** [Akascape/CTkTable#95]
`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\core_widget_classes\ctk_base_class.py", line 188, in _update_dimensions_event
    self._draw(no_color_updates=True)  # faster drawing without color changes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 187, in _draw
    self._draw_engine.draw_background_corners(self._apply_widget_scaling(self._current_width),
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\core_rendering\draw_engine.py", line 72, in draw_background_corners
    if not self._canvas.find_withtag("background_corner_top_left"):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2922, in find_withtag
    return self.find('withtag', tagOrId)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2889, in find    
    self.tk.call((self._w, 'find') + args)) or ()      
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: invalid command name ".!ctkframe.!ctkframe2.!canvas.!ctkscrollableframe.!ctkframe2.!ctkframe.!canvas.!ctkxyframe.!ctktable.!ctkframe.!ctkbutton5.!ctkcanvas"`

I'm sorry I'm still a beginner in building GUIs. I want to know what causes this to happen, some references I'm looking for the result is because the widget that has been destroyed wants to be accessed again, the problem is in my code I never destroy the widget, do you have any suggestions to solve this problem? thank you for helping

**Comment by Akascape** [comment]
@Adhitya-02 Provide the code for testing...

**Comment by Adhitya-02** [comment]
I apologies in advance for asking about the error, now I have successfully solved the error, the possibility that happened was that I made a function with an algorithm that was too complex, now I have made it simpler. Thank you very much for your attention and keep the spirit to develop this widget you are very helpful.
